services:
  backend:
    build:
      context: .
      dockerfile: Containerfile
      target: backend

    volumes:
      - ./src:/app/src
      - tmp-data:/var/tmp
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - RABBIT_URL=amqp://rabbit
    depends_on:
      - worker

    command: ["uvicorn", "src.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]


  rabbit:
    image: rabbitmq:3.12.0-alpine
    ports:
      - "5673:5673"

  worker:
    build:
      context: .
      dockerfile: Containerfile
    hostname: worker
    entrypoint: celery
    command: -A tasks worker --loglevel=info
    volumes:
      - ./src:/app/src
      - tmp-data:/var/tmp
    environment:
      - RABBIT_URL=amqp://rabbit
    depends_on:
      - rabbit

volumes:
  tmp-data: